### ISSUE TITLE
Zusatzrechnung Folder-Verkauf

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/simple-courses#153]
- - - -
### Requirements
- - - -
Ich dachte wir machen dafür einen eigenen Nummernkreis – Florinda passt das, z.B. vorne statt 108 - 111?    
**Ja das passt super so.**
 
Es folgt dann noch eine separate Bankverbindung dafür – teile ich Dir mit, sobald ich sie habe.    
**Habe ich beantragt wird aber noch dauern.**
 
Es kann immer nur in 100-Stück-Packungen bestellt werden. Ist es möglich eine Bestellung von mehreren hundert Stück abzubilden?
Also 200 Stück sollte dann stehen und der Preis entsprechend verdoppelt.
Oder wenn das schwierig ist könnte man auch eine zweite Rechnung für die zweite Packung ausstellen, ist natürlich nicht so elegant.    
**Hier könnte man eventuell es so machen, dass so Kästchen sind die dann angekreuzt werden für die 100 er Pakete.
Ich denke es werden nicht mehr als 3 Pakete gekauft.
Somit ein Kästchen 100 Stk. Flyer/Folder – 18€
Nächste Zeile Kästchen 200 Stk. Flyer/Folder – 36€
Nächte Zeile Kästchen 300 Stk. Flyer/Folder – 54€**
 
 
Die Folder können immer nur beim Kurs gekauft werden und das ist auch für mich im Handling am einfachsten wenn es beim Kurs verrechnen kann.
Es wäre aber schön, wenn es dann auch beim Kunden sichtbar ist. Schau mal welcher Workflow Dir da einfällt, danke!

Let's bring it live together with #97

[Rechnungsvorlage_Folderverkauf.pdf](https://github.com/viszerale-therapie/simple-courses/files/2413970/Rechnungsvorlage_Folderverkauf.pdf)

---------
### Technical Concept
- - - -

* New Database **Product**
    * Id
    * name
    * qtySteps
    * price

* New Database Table **Order**
    * Customer
    * date
    * productLines (json)
    * total (money)
    * Course (nullable)

* Configuration via new Menu Point in Setup: **Product Prices**

- - - -
### Todos
- - - -
* [x] Spalte _Folder, Stückzahl_ in der Teilnehmerliste hinzufügen
* [x] Preis über konfiguration
* [x] Overlay zum generieren, prüfen und versenden der Rechnungen am Kurs
* [x] "Combined PDF" und "Zip" funktionalität
* [x] Orders im System ablegen
* [x] Preview pdf
* [x] Allow individual page types per pdf
* [x] Preview Email
* [x] Rechnungs Template (#97)
* [x] Email Template (#97)
* [x] Sichtbarkeit am Kunden ( Hat Seiteneffekte und muss mit #124 überbrückt werden)

- - - -
### Deployment

* [x] Email Template prüfen
* [x] Rechnungs Template prüfen
* [x] Folder pdf Frame prüfen
* [x] Produkt Konfigurieren
- - - -

**Comment by Andreas-Schoenefeldt** [comment]
Ja klar, die Spalte nenne ich dann *Folder*?

**Comment by ursulafeu** [comment]
bitte so, dann ist es selbsterklärend:
Folder, Stückzahl

**Comment by Andreas-Schoenefeldt** [comment]
Liebe @ursulafeu,

we proudly preset the: Folder Invoice Feature :D 

Das ganze ist wie schon gesagt zusammen mit #97 (pdf Rechnung bei Anmeldung) verheiratet, so dass es bitte einmal vom Flow her geprüft werden muss.

Hier ist das test Backend: http://backend-test.czeija.com 
Hier findest du Testkurse, bei denen du über das test-frontend Anmeldungen machen kannst (Die Test Frontent Seite sonst bitte grnorieren, der Inhalt ist nicht mit live identisch)

@nmxmx, falls du die Tage Zeit hast auch noch einmal den Flow zu testen, wäre das toll.

Ich fixe noch die kleinen Fehler, die Nicole schon gefunden hat und wenn dann von euch das ok kommt, können wir das Feature live stellen.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
großartig! Ich hoffe ich kann es gleich morgen Vormittag testen, danke!

**Comment by ursulafeu** [comment]
Lieber Andreas, erstmal DANKE! :) Das ist richtig klasse, ich freu mich sehr, dass wir das jetzt haben. Ein paar Kleinigkeiten hab ich beim Testen noch gefunden:

1) bitte auch die Funktion "Combined PDF" und "Zip" hinzufügen, beides brauche ich jedesmal beim Rechnungen schreiben.
2) Beim Versand der Folder-Invoice an mich selbst kommt Fehlermeldung: 
Sorry, something went wrong: Internal Server Error
(getestet bei Course ID 240 - habe nur 1 Empfänger ausgewählt)

**Comment by ursulafeu** [comment]
PS: Der Versand einer normalen Rechnung im Test-System hat funktioniert.

**Comment by ursulafeu** [comment]
Beim Kunden würd ich auch gern noch sehen, ob er Folder gekauft hat. Das ist wichtig fürs Marketing und auch Controlling. Meine Lösungsideen: 
- Häkchen (so wie beim Diplom) und dann wäre noch extrem cool, wenn wir irgendwie das Datum beim Download der Kundenliste also Info dabei haben. Also Kursmonat und Jahr. Geht das?
...
Template Texteingabe usw ist super gelöst, danke.

**Comment by ursulafeu** [comment]
Rechnungs-PDF stimmt noch nicht:
1) Anschrift wird nicht ausgegeben
2) Stückzahl wird nicht übernommen, da steht immer Null
3) Rechnungszusatz unten mit Bankverbindung bitte anpassen (siehe PDF anbei)

**Comment by ursulafeu** [comment]
Rechnungs-PDF stimmt noch nicht:
1) Anschrift wird nicht ausgegeben
2) Stückzahl wird nicht übernommen, da steht immer Null
3) Rechnungszusatz unten mit Bankverbindung bitte anpassen (siehe PDF anbei)

**Comment by ursulafeu** [comment]
/Users/ursula/Downloads/Kreundl_Petra_108_240Folder_Rechnung.pdf

**Comment by ursulafeu** [comment]
Ich kann hier kein PDF hochladen. Ich schick Dir die beiden PDFs per Email.

**Comment by Andreas-Schoenefeldt** [comment]
Sehr cool, das klingt ja schon ganz gut - ich suche mal die Fehler und melde mich dann wieder bei dir.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Lieber Andreas, ich hab hier einen Stapel Rechnungen zu schreiben, denkst Du ich kann es abwarten bis es im System ist? :)

**Comment by Andreas-Schoenefeldt** [comment]
Ich versuche heute die Änderungen einzuspielen - bin gerade etwas zu viel am balancieren.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo @ursulafeu,

bis auf die Sichtbarkeit am Customer sollten die offenen Punkte jetzt gut sein. Kannst du bitte nochmal auf dev prüfen?

Die Sichtbarkeit am Customer versuche ich jetzt umzusetzen. Mir schwebt so ein overlay vor, in dem die Anmeldungen, Qualifikationen und Bestellungen des Customers zu sehen sind.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Hi lieber Andreas,
bei mir ist grad alles auf Pause weil ich krank bin. Eitrige Mittelohr Entzündung, seit langem mal wirklich krank, mag nur liegen...
Also nicht wundern, dass da nix kommt von mir auf das lang ersehnte Tool. I‘ll be back! 😎
Liebe Grüße, Ursula 

Von meinem iPhone gesendet

**Comment by Andreas-Schoenefeldt** [comment]
No Problem und Gute Besserung! 

Die sichtbarkeit am Kunden hat hier eh nochmal voll die Baustelle aufgemacht. 
Dabei werden aber gleich ein paar andere Tickets, die wir auch schon lange auf der Warteliste haben mit fallen ;)

Ich hoffe ich bekomm es heute abschließend durch.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Wie kommt eigentlich der "Status" beim Kunden zustande?

**Comment by ursulafeu** [comment]
- Die Einzel-PDFs als zip funktionieren noch nicht.
- Und die Sichtbarkeit am Kunden. 
- Sonst siehts gut aus für mich! :)

**Comment by ursulafeu** [comment]
Beim Download als zip sehen die PDFs dann so mit Fehlermeldung aus:
Oops! An Error Occurred
The server returned a "401 Unauthorized".
Something is broken. Please let us know what you were doing when this error occurred. We will
fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by Andreas-Schoenefeldt** [comment]
Hi @ursulafeu,

ich denke jetzt ist es so, wie es sein soll :) - Die Zusatzbestellungen sind jetzt auch am Customer sichtbar und können dort bei bedarf auch gelöscht werden.

Liebe Grüße und danke fürs Testen ;)
Andreas

**Comment by ursulafeu** [comment]
Uuuuuhh!!! Ist es schon live?

Von meinem iPhone gesendet

**Comment by Andreas-Schoenefeldt** [comment]
Auf der Testumgebung, ja - ich muss aber nochmal die Punkte prüfen, die du angemerkt hast und habe selber gestern auch zwei Fehler gefunden.

Die Status Zeile habe ich wieder ins backend verbannt - das macht für den User keinen Sinn. Wichtig ist nur zu wissen, das ein automatischer Prozess alle 5 minuten die emails und pdfs generiert und verschickt - eventuell kann es dabei natürlich zu Fehlern kommen - dann wird die Zeile jetzt rot (was hoffentlich nie passier ;) ).

Liebe Grüße
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
Das "Download Zip" ist jetzt auch gefixed :).

**Comment by Andreas-Schoenefeldt** [comment]
Ich glaub jetzt haben wir so ziemlich alle Fehler, ich hab jetzt ein gutes Gefühl :) @nmxmx hatte auch noch ein paar Frontend Issues gefunden, die würde ich dann morgen angehen.

Gebt ihr euer ok, falls ihr nicht noch etwas findet?

**Comment by ursulafeu** [comment]
Ich hab grad nochmal getestet:
1) Email-Versenden bringt einen internen Error, das geht nicht (ist aber vermutlich im Test-System nicht möglich?
2) Im PDF ist noch ein Tippfehler:
Herzlichen Dank,
Schule für Viszerale Therapie
und integrative manuelle Behandlungsmethode
--> da fehlt ganz am Ende das "n" (Behandlungsmethoden)

**Comment by ursulafeu** [comment]
Noch eine Textänderung im PDF: 
Bankverbindung auch in der Fußzeile anpassen bitte:
IBAN AT50 1420 0200 1271 8455
BIC EASYATW1

**Comment by ursulafeu** [comment]
Lieber Andreas, wie ist die Lage?

**Comment by Andreas-Schoenefeldt** [comment]
Ich muss noch die letzten Änderungen zu den erwähnten issues machen - ich melde mich heute noch mit dem Startschuss der hoffentlich letzten Runde.

**Comment by Andreas-Schoenefeldt** [comment]
Liebe Ursula,

1. Hat bei mir geklappt - vielleicht war das nur ein Schluckauf? Versuch es mal bitte noch einmal.
2. Ist geändert :)

Für mich sieht eigentlich soweit alles gut aus - wenn du nicht noch etwas findest, würde ich sagen wir haben unseren Live Kandidaten.

Ich mache jetzt noch die issues, die Nicole im Frontend gefunden hat und warte dann auf dein GO ;)

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Schaut alles gut aus für mich - let's do it! Gerne live stellen. juhu!
